// Code generated by goctl. DO NOT EDIT.
package types

type ActionReply struct {
	ID          int64  `json:"id"`
	UserId      int64  `json:"user_id"`
	MerchantId  int64  `json:"merchant_id"`
	ContentList string `json:"content_list"`
}

type ActionRequest struct {
	ActionID int64 `path:"id"`
}

type GetUserInfoReply struct {
	ID        int64  `json:"user_id"`
	Name      string `json:"name"`
	ImageId   int64  `json:"image_id"`
	Sex       int    `json:"sex"`
	TelePhone int64  `json:"telephone"`
	CartId    int64  `json:"cart_id"`
	Desc      string `json:"desc"`
}

type GetUserInfoRequest struct {
	UserID int64 `path:"id"`
}

type GoodsReply struct {
	ID          int64  `json:"id"`
	GoodsName   string `json:"good_name"`
	Price       int64  `json:"price"`
	ImageIdList string `json:"image_id_list"`
	Desc        string `json:"desc"`
	MerchantId  string `json:"merchant"`
	State       int64  `json:"state"`
	Amount      int64  `json:"amount"`
}

type GoodsRequest struct {
	GoodId int64 `path:"id"`
}

type ImageReply struct {
	ID          int64  `json:"id"`
	ImageBase64 string `json:"imagebase64"`
}

type ImageRequest struct {
	ImageId int64 `path:"id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type OrderReply struct {
	ID                int64  `json:"id"`
	UserId            int64  `json:"user_id"`
	MerchantId        int64  `json:"merchant_id"`
	OrderProductsList string `json:"order_products_list"`
}

type OrderRequest struct {
	ActionID int64 `path:"id"`
}

type RegisterReply struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type RegisterRequest struct {
	ID        int64  `json:"user_id"`
	Name      string `json:"name"`
	ImageId   int64  `json:"image_id"`
	Sex       int    `json:"sex"`
	TelePhone int64  `json:"telephone"`
	CartId    int64  `json:"cart_id"`
	Desc      string `json:"desc"`
}

type UserCartReply struct {
	CartID      int64  `json:"cart_id"`
	ProductList string `json:"product_list"`
}

type UserCartRequest struct {
	CartID int64 `path:"id"`
}
