// Code generated by goctl. DO NOT EDIT.
package types

type ActionListResp struct {
	ActionIdList []int64 `json:"action_id_list"`
}

type ActionReq struct {
	ActionID int64 `json:"action_id"`
}

type ActionResp struct {
	ActionID    int64     `json:"action_id"`
	UserId      int64     `json:"user_id"`
	MerchantId  int64     `json:"merchant_id"`
	ContentList []Content `json:"content_list"`
}

type Auth struct {
	Token        string `json:"token"`
	Expire       int64  `json:"expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type Cart struct {
	CartProductList []CartProduct `json:"cart_product_list"`
}

type CartProduct struct {
	ProductId int64 `json:"id"`
	Number    int   `json:"number"`
}

type Content struct {
	OwnerId int64  `json:owner`
	Date    int64  `json:"date"`
	Text    string `json:"text"`
}

type DateScope struct {
	StartDate string `json:"start_date"`
	EndDate   string `json:"end_date"`
}

type DeleteActionReq struct {
	ActionID int64 `json:"action_id"`
}

type DeleteProductReq struct {
	ID int64 `path:"id"`
}

type DeleteUserReq struct {
}

type DeleteUserResp struct {
}

type Image struct {
	ImageId     int64  `json:"id"`
	ImageBase64 string `json:"imagebase64"`
}

type ImageId struct {
	Id int64 `json:"id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Status  int64  `json:"status"`
	Message string `json:"message"`
	Auth    Auth   `json:"auth"`
}

type NameAvailableReq struct {
	Name string `json:"name"`
}

type NameAvailableResp struct {
	Status int64 `json:"status"`
}

type NewActionReq struct {
	MerchantId int64 `json:"merchant_id"`
}

type NewActionResp struct {
	ActionID int64 `json:"action_id"`
}

type NewImage struct {
	ImageBase64 string `json:"imagebase64"`
}

type NewOrder struct {
	UserId           int64          `json:"user_id"`
	OrderProductList []OrderProduct `json:"order_product_list"`
}

type NewProduct struct {
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	ImageIdList []int64 `json:"image_id_list"`
	Desc        string  `json:"desc"`
	State       int     `json:"state"`
	Amount      int64   `json:"amount"`
}

type Order struct {
	UserId           int64          `json:"user_id"`
	MerchantId       int64          `json:"merchant_id"`
	Date             string         `json:"date"`
	State            int64          `json:"state"`
	LogisticsIdList  []int64        `json:"logistics_id_list"`
	OrderProductList []OrderProduct `json:"order_product_ist"`
}

type OrderId struct {
	Id int64 `json:"id"`
}

type OrderIdList struct {
	OrdersIdList []int64 `json:"orders_id_list"`
}

type OrderProduct struct {
	ProductId int64   `json:"id"`
	Number    int64   `json:"number"`
	Price     float64 `json:"price"`
}

type Product struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	ImageIdList []int64 `json:"image_id_list"`
	Desc        string  `json:"desc"`
	MerchantId  int64   `json:"merchant"`
	State       int     `json:"state"`
	Amount      int64   `json:"amount"`
}

type ProductId struct {
	Id int64 `json:"id"`
}

type RandomProductIdListResp struct {
	ProductIdList []int64 `json:"id_list"`
}

type RegisterReq struct {
	Name      string `json:"name"`
	Password  string `json:"password"`
	Sex       int    `json:"sex"`
	TelePhone int64  `json:"telephone"`
	Intro     string `json:"intro"`
}

type RegisterResp struct {
	Status  int64  `json:"status"`
	Message string `json:"message"`
	Auth    Auth   `json:"auth"`
}

type UpdateActionReq struct {
	ActionID int64   `json:"action_id"`
	Content  Content `json:"content"`
}

type UpdateProductReq struct {
	ID          int64   `path:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	ImageIdList string  `json:"image_id_list"`
	Desc        string  `json:"desc"`
	State       int     `json:"state"`
	Amount      int64   `json:"amount"`
}

type UpdateUserInfoReq struct {
	Name      string `json:"name"`
	ImageId   int64  `json:"image_id"`
	Sex       int    `json:"sex"`
	TelePhone int64  `json:"telephone"`
	Intro     string `json:"intro"`
}

type UpdateUserInfoResp struct {
}

type UserInfoResp struct {
	Name      string `json:"name"`
	ImageId   int64  `json:"image_id"`
	Sex       int    `json:"sex"`
	TelePhone int64  `json:"telephone"`
	Desc      string `json:"desc"`
}
