// Code generated by goctl. DO NOT EDIT.
package types

type AddActionContentRequest struct {
	ID         int64  `path:"id"`
	NewContent string `json:"content"`
}

type AddProductRequest struct {
	Name        string `json:"name"`
	Price       int64  `json:"price"`
	ImageIdList string `json:"image_id_list"`
	Desc        string `json:"desc"`
	State       int64  `json:"state"`
	Amount      int64  `json:"amount"`
}

type CreateActionReply struct {
	ID int64 `json:"id"`
}

type CreateActionRequest struct {
	UserId     int64 `json:"user_id"`
	MerchantId int64 `json:"merchant_id"`
}

type CreateOrderRequest struct {
	UserId       int64  `json:"user_id"`
	TotalPaid    int64  `json:"total_paid"`
	ProductsList string `json:"products_list"`
}

type DeleteActionRequest struct {
	ID int64 `path:"id"`
}

type DeleteOrderRequest struct {
	OrderId int64 `path:"id"`
}

type DeleteProductRequest struct {
	ID int64 `path:"id"`
}

type GetActionListReply struct {
	ActionIdList []int64 `json:"action_id_list"`
}

type GetActionReply struct {
	ID          int64    `json:"id"`
	UserId      int64    `json:"user_id"`
	MerchantId  int64    `json:"merchant_id"`
	ContentList []string `json:"content_list"`
}

type GetActionRequest struct {
	ActionID int64 `path:"id"`
}

type GetAllProductReply struct {
	ProductIdList []int64 `json:"id_list"`
}

type GetCartReply struct {
	ProductsList []string `json:"products_list"`
}

type GetImageReply struct {
	ImageBase64 string `json:"imagebase64"`
}

type GetImageRequest struct {
	ImageId int64 `path:"id"`
}

type GetOrderReply struct {
	UserId          int64  `json:"user_id"`
	Date            string `json:"date"`
	State           int64  `json:"state"`
	LogisticsIdList int64  `json:"logistics_id_list"`
	TotalPaid       int64  `json:"total_paid"`
	ProductsList    string `json:"products_list"`
}

type GetOrderRequest struct {
	OrderId int64 `path:"id"`
}

type GetOrdersReply struct {
	OrdersIdList []int64 `json:"orders_id_list"`
}

type GetOrdersRequest struct {
	StartDate string `json:start_date`
	EndDate   string `json:end_date`
}

type GetProductReply struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Price       int64  `json:"price"`
	ImageIdList string `json:"image_id_list"`
	Desc        string `json:"desc"`
	MerchantId  string `json:"merchant"`
	State       int64  `json:"state"`
	Amount      int64  `json:"amount"`
}

type GetProductRequest struct {
	ProductId int64 `path:"id"`
}

type GetUserInfoReply struct {
	Name      string `json:"name"`
	ImageId   int64  `json:"image_id"`
	Sex       int    `json:"sex"`
	TelePhone int64  `json:"telephone"`
	Desc      string `json:"desc"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Token        string `json:"token"`
	Expire       int64  `json:"expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type PutImageReply struct {
	ID int64 `json:"image_id"`
}

type PutImageRequest struct {
	ImageBase64 string `json:"imagebase64"`
}

type PutUserInfoRequest struct {
	Name      string `json:"name"`
	ImageId   int64  `json:"image_id"`
	Sex       int    `json:"sex"`
	TelePhone int64  `json:"telephone"`
	Intro     string `json:"intro"`
}

type RegisterRequest struct {
	Name      string `json:"name"`
	Password  string `json:"password"`
	Sex       int    `json:"sex"`
	TelePhone int64  `json:"telephone"`
	Intro     string `json:"intro"`
}

type UpdateProductRequest struct {
	ID          int64  `path:"id"`
	Name        string `json:"name"`
	Price       int64  `json:"price"`
	ImageIdList string `json:"image_id_list"`
	Desc        string `json:"desc"`
	State       int64  `json:"state"`
	Amount      int64  `json:"amount"`
}

type UpdateProductToCartRequest struct {
	ProductId  int64 `json:"product_id"`
	ProductNum int64 `json:"product_num"`
}
