// Code generated by goctl. DO NOT EDIT.
package types

type ActionContentReq struct {
	ActionID  int   `json:"Action_id"`
	StartTime int64 `json:"start_time"`
	EndTime   int64 `json:"end_time"`
}

type ActionContentResp struct {
	ActionID     int       `json:"Action_id"`
	Content_List []Content `json:"content_list"`
}

type ActionCreateReq struct {
	MerchantId int `json:"merchant_id"`
}

type ActionCreateResp struct {
	ActionID int `json:"action_id"`
}

type ActionDeleteReq struct {
	ActionID int64 `json:"action_id"`
}

type ActionListResp struct {
	ActionIdList []int `json:"action_id_list"`
}

type ActionReq struct {
	ActionID int64 `json:"action_id"`
}

type ActionResp struct {
	ActionID   int `json:"action_id"`
	UserId     int `json:"user_id"`
	MerchantId int `json:"merchant_id"`
}

type ActionUpdateReq struct {
	ActionID int     `json:"action_id"`
	Content  Content `json:"content"`
}

type Auth struct {
	Token        string `json:"token"`
	Expire       int    `json:"expire"`
	RefreshAfter int    `json:"refresh_after"`
}

type Cart struct {
	CartProductList []CartProduct `json:"cart_product_list"`
}

type CartProduct struct {
	ProductId int   `json:"id"`
	Number    int   `json:"number"`
	Date      int64 `json:"date`
}

type Content struct {
	OwnerId int64  `json:"owner"`
	Date    int64  `json:"date"`
	Text    string `json:"text"`
}

type DateScope struct {
	StartDate int64 `json:"start_date"`
	EndDate   int64 `json:"end_date"`
}

type DeleteProductReq struct {
	ID int `path:"id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Id      int    `json:"id"`
	Name    string `json:"name"`
	State   int    `json:"state"`
	Message string `json:"message"`
	Auth    Auth   `json:"auth"`
}

type NameAvailableReq struct {
	Name string `json:"name"`
}

type NameAvailableResp struct {
	State int `json:"state"`
}

type NewOrder struct {
	UserId           int            `json:"user_id"`
	Remark           string         `json:"remark"`
	OrderProductList []OrderProduct `json:"order_product_list"`
}

type NewProduct struct {
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	AvatarId    string  `json:"avatar_id"`
	ImageIdList []int   `json:"image_id_list"`
	Desc        string  `json:"desc"`
	State       int     `json:"state"`
	Amount      int     `json:"amount"`
}

type Order struct {
	UserId           int            `json:"user_id"`
	MerchantId       int            `json:"merchant_id"`
	Date             int64          `json:"date"`
	State            int            `json:"state"`
	Remark           string         `json:"remark"`
	OrderProductList []OrderProduct `json:"order_product_ist"`
}

type OrderId struct {
	Id int `json:"id"`
}

type OrderIdList struct {
	OrdersIdList []int `json:"orders_id_list"`
}

type OrderProduct struct {
	ProductId int     `json:"id"`
	Number    int     `json:"number"`
	Price     float64 `json:"price"`
	Logistics string  `json:"logistics"`
}

type Product struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	AvatarId    string  `json:"avatar_id"`
	ImageIdList []int   `json:"image_id_list"`
	Desc        string  `json:"desc"`
	MerchantId  int     `json:"merchant"`
	State       int     `json:"state"`
	Amount      int     `json:"amount"`
}

type ProductId struct {
	Id int `json:"id"`
}

type RandomProductIdListResp struct {
	ProductIdList []int `json:"id_list"`
}

type RegisterReq struct {
	Name      string `json:"name"`
	Password  string `json:"password"`
	Sex       int    `json:"sex"`
	TelePhone int    `json:"telephone"`
	Intro     string `json:"intro"`
}

type RegisterResp struct {
	State   int    `json:"state"`
	Message string `json:"message"`
	Auth    Auth   `json:"auth"`
}

type UpdateProductReq struct {
	ID          int      `path:"id"`
	Name        string   `json:"name"`
	Price       float64  `json:"price"`
	AvatarId    string   `json:"avatar_id"`
	ImageIdList []string `json:"image_id_list"`
	Desc        string   `json:"desc"`
	State       int      `json:"state"`
	Amount      int      `json:"amount"`
}

type UserDeleteReq struct {
}

type UserDeleteResp struct {
}

type UserInfoResp struct {
	Name      string `json:"name"`
	ImageId   string `json:"image_id"`
	Sex       int    `json:"sex"`
	TelePhone int    `json:"telephone"`
	Desc      string `json:"desc"`
}

type UserInfoUpdateReq struct {
	Name      string `json:"name"`
	ImageId   string `json:"image_id"`
	Sex       int    `json:"sex"`
	TelePhone int    `json:"telephone"`
	Intro     string `json:"intro"`
}

type UserInfoUpdateResp struct {
}
