// Code generated by goctl. DO NOT EDIT.
package types

type ImageIndex struct {
	ImageHash string `json:"hash"`
	Message   string `json:"message"`
}

type ImageReq struct {
	ImageBase64 string `json:"base64"`
}

type ImageResp struct {
	ImageHash   string `json:"hash"`
	ImageBase64 string `json:"base64"`
}
